M48
; DRILL file {KiCad 7.0.7} date Wed Nov 27 08:57:54 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-27T08:57:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0900
%
G90
G05
T1
X8.4545Y-2.2244
X8.6455Y-2.2244
T2
X8.4427Y-2.1051
X8.6573Y-2.1051
T3
X3.575Y-3.275
X3.575Y-4.975
X6.575Y-4.975
T4
X3.666Y-4.125
X5.084Y-4.125
X5.516Y-4.125
X6.934Y-4.125
T0
M30
